import { ChessAgent } from "@/types/agent";

export const mockAgents: ChessAgent[] = [
  {
    id: "1",
    name: "Magnus Bot",
    personality: "A calm and calculated AI that favors positional play and long-term strategy. Never rushes into tactics without solid groundwork.",
    playstyle: "Positional",
    firstMove: "d4",
    marketCap: 2850,
    elo: 2850,
    wins: 127,
    losses: 23,
    draws: 18,
    owner: "0x1234...5678",
    createdAt: new Date("2026-01-15"),
  },
  {
    id: "2",
    name: "Chaos Engine",
    personality: "Unpredictable and wild, this bot thrives on creating complex positions and confusing opponents with unconventional moves.",
    playstyle: "Chaotic",
    firstMove: "f4",
    marketCap: 2720,
    elo: 2720,
    wins: 98,
    losses: 45,
    draws: 31,
    owner: "0xabcd...ef01",
    createdAt: new Date("2026-01-18"),
  },
  {
    id: "3",
    name: "The Aggressor",
    personality: "Relentlessly attacking from the first move. This bot believes the best defense is a crushing offense.",
    playstyle: "Aggressive",
    firstMove: "e4",
    marketCap: 2680,
    elo: 2680,
    wins: 105,
    losses: 38,
    draws: 22,
    owner: "0x9876...5432",
    createdAt: new Date("2026-01-20"),
  },
  {
    id: "4",
    name: "Fortress",
    personality: "A defensive mastermind that waits for opponents to overextend, then strikes with precision counterattacks.",
    playstyle: "Defensive",
    firstMove: "c4",
    marketCap: 2590,
    elo: 2590,
    wins: 82,
    losses: 29,
    draws: 47,
    owner: "0x5555...aaaa",
    createdAt: new Date("2026-01-22"),
  },
  {
    id: "5",
    name: "Harmony",
    personality: "Seeks perfect balance between attack and defense, adapting to the opponent's style with flexibility.",
    playstyle: "Balanced",
    firstMove: "Nf3",
    marketCap: 2540,
    elo: 2540,
    wins: 73,
    losses: 31,
    draws: 38,
    owner: "0xbbbb...cccc",
    createdAt: new Date("2026-01-23"),
  },
  {
    id: "6",
    name: "Gambit Master",
    personality: "Lives for sacrifices and tactical fireworks. Every game is a chance to showcase brilliant combinations.",
    playstyle: "Aggressive",
    firstMove: "e4",
    marketCap: 2480,
    elo: 2480,
    wins: 89,
    losses: 52,
    draws: 19,
    owner: "0xdddd...eeee",
    createdAt: new Date("2026-01-25"),
  },
  {
    id: "7",
    name: "Hypermodern",
    personality: "Controls the center from afar with fianchettoed bishops and flexible pawn structures.",
    playstyle: "Positional",
    firstMove: "g3",
    marketCap: 2410,
    elo: 2410,
    wins: 61,
    losses: 28,
    draws: 44,
    owner: "0xffff...1111",
    createdAt: new Date("2026-01-26"),
  },
  {
    id: "8",
    name: "Rookie Rush",
    personality: "A newcomer with more enthusiasm than experience, but shows promising tactical vision.",
    playstyle: "Chaotic",
    firstMove: "b3",
    marketCap: 2200,
    elo: 2200,
    wins: 34,
    losses: 41,
    draws: 15,
    owner: "0x2222...3333",
    createdAt: new Date("2026-01-28"),
  },
];
